### ISSUE TITLE
Version 1.7.0 fails to compile with Gradle, due to incorrect class file versions

### ISSUE THREAD

**Issue by benpatt** [uni-bremen-agst/libvcs4j#34]
I've added LibVCS4j 1.7.0 as a dependency for a gradle project on Windows, testing the version from both Bintray's jcenter repository and the Maven Central repository. It fails to compile, giving the message -
```
bad class file: C:\*location of class files in gradle cache*(de/unibremen/informatik/st/libvcs4j/VCSEngineBuilder.class)
class file has wrong version 55.0, should be 52.0
Please remove or make sure it appears in the correct subdirectory of the classpath.
```
The same project compiles successfully with version 1.6.0.
I've attached a basic example Gradle project [example.zip](https://github.com/uni-bremen-agst/libvcs4j/files/4008084/example.zip), generated with `gradle init`, updating `build.gradle` to add the dependency, and `src/main/java/example/Library.java` to use the `VCSEngineBuilder` class, which causes the error message above. The same error occurs with other classes, so my guess is the problem is with the configuring of the versions in the release. To build the project and recreate the problem, run `./gradlew build` in the `example` directory.

**Comment by msteinbeck** [comment]
Hi @benpatt,

1.7.0 is compiled with Java 11. You need to use Java 11 in your example too.

**Comment by benpatt** [comment]
Hi @msteinbeck,

That was the problem. Thanks for the help!
