### ISSUE TITLE
Comparison of unrelated commits in the presence of multiple concurrent branches

### ISSUE THREAD

**Issue by holgerknoche** [uni-bremen-agst/libvcs4j#37]
When a revision range contains a merge of two or more concurrent branches, unrelated commits from these branches are considered as related when they interleave in time. For instance, consider the following situation: commit c1@branch b2@timestamp t1, c2@b2@t2 and c3@b1@t3 such that t1 < t2 < t3 and there are no commits between these three. Furthermore, branches b1 and b2 are merged in a later commit within the range. Then, iterating over the revision range will visit the three commits in the order of their timestamps, and the diff at commit c2 will be created with respect to c3 although these two commits are unrelated, resulting in wrong diffs.

**Comment by msteinbeck** [comment]
Git's option: `--first-parent`  may solves this issue:

_Follow only the first parent commit upon seeing a merge commit. This option can give a better overview when viewing the evolution of a particular topic branch, because merges into a topic branch tend to be only about adjusting to updated upstream from time to time, and this option allows you to ignore the individual commits brought in to your history by such a merge._

Maybe JGit offers a corresponding method.

**Comment by holgerknoche** [comment]
According to the description, that option addresses the issue. Unfortunately, I have not found a method to pass this option to the JGit implementation, not even in the current version (5.6).

**Comment by holgerknoche** [comment]
I have prepared a local branch providing "--first-parent" behavior, but I do not seem to have the rights to create a branch in the repository. Can you please give me the appropriate rights or a pointer on how to create a pull request without them?

**Comment by msteinbeck** [comment]
Thank you for working on this issue. You need to fork this project and push your changes into your fork. Git will then propose to create a pull request.

1. Press the `Fork` button on the top-right.
2. Clone your fork. The URL should be: https://github.com/holgerknoche/libvcs4j.git
3. You can (but do not need to) create a branch.
4. Commit your changes and push them.
5. Create the pull request.

You can find more details at: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
